[package]
name = "xor-hash-accumulator"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
digest = "0.10"
rayon = { version = "1", optional = true }

[dev-dependencies]
blake3 = { version = "1", features = ["traits-preview"] }

[features]
default = []
rayon = ["dep:rayon"]
